### PR TITLE
fix(dynamo): divide GSI consumed RCU/WCU metrics by period

### LINKED ISSUE #362: DynamoDB GSI Consumed Metrics are Wrong
### Version

v4.0.3

### Steps and/or minimal code example to reproduce

Using `.monitorDynamoTableGlobalSecondaryIndex(…)` creates a widget and monitors that use an incorrect metric for the consumed values.

### Expected behavior

As with the consumed metrics when using `.monitorDynamoTable(…)`, the metrics need to be divided by the number of periods:

https://github.com/cdklabs/cdk-monitoring-constructs/blob/main/lib/monitoring/aws-dynamo/DynamoTableMetricFactory.ts#L58-L80

### Actual behavior

This logic is missing for the consumed metrics for GSIs:

https://github.com/cdklabs/cdk-monitoring-constructs/blob/main/lib/monitoring/aws-dynamo/DynamoTableGlobalSecondaryIndexMetricFactory.ts#L50-L70

### Other details

_No response_

### PR DESCRIPTION
**Pull request by echeung-amzn**
Fixes #362

Results in a dashboard widget with a source like:

```
{
    "view": "timeSeries",
    "title": "Read Capacity",
    "region": "us-east-1",
    "metrics": [
        [ { "label": "Consumed", "expression": "consumed_rcu_sum/PERIOD(consumed_rcu_sum)", "region": "us-east-1" } ],
        [ "AWS/DynamoDB", "ConsumedReadCapacityUnits", "GlobalSecondaryIndexName", "SampleTable2-GSI", "TableName", "SampleTable2", { "stat": "Sum", "visible": false, "id": "consumed_rcu_sum", "region": "us-east-1" } ],
        [ ".", "ProvisionedReadCapacityUnits", ".", ".", ".", ".", { "label": "Provisioned", "stat": "Sum", "region": "us-east-1" } ]
    ],
    "yAxis": {
        "left": {
            "min": 0,
            "label": "Count",
            "showUnits": false
        }
    },
    "timezone": "UTC"
}
```

---

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license_

### CODE REVIEW

File: lib/monitoring/aws-dynamo/DynamoTableGlobalSecondaryIndexMetricFactory.ts [hunk 1]
```diff
@@ -48,24 +50,28 @@ export class DynamoTableGlobalSecondaryIndexMetricFactory {
...
-      DynamoDbNamespace
+    return this.metricFactory.createMetricMath(
+      "consumed_rcu_sum/PERIOD(consumed_rcu_sum)",
+      {
+        consumed_rcu_sum: this.table.metricConsumedReadCapacityUnits({
+          statistic: MetricStatistic.SUM,
+          dimensionsMap: this.dimensionsMap,
+        }),
+      },
+      "Consumed"
```
Comment (ayush987goyal) [inline lib/monitoring/aws-dynamo/DynamoTableGlobalSecondaryIndexMetricFactory.ts:61]: Why can't we just use the metric provided by the table construct?

Comment (echeung-amzn) [reply lib/monitoring/aws-dynamo/DynamoTableGlobalSecondaryIndexMetricFactory.ts:61]: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_dynamodb.Table.html#metricwbrconsumedwbrreadwbrcapacitywbrunitsprops

> By default, the metric will be calculated as a sum over a period of 5 minutes. You can customize this by using the `statistic` and `period` properties.

We'd want to adapt this to whatever the relevant period is similar to what's being done for the non-GSI DDB metrics as mentioned in #362.

**Review by ayush987goyal — APPROVED** [review]
